project:
  type: book
  output-dir: docs

book:
  title: "Raciocíno clínico"
  author: "Adelson Guaraci Jantsch"
  date: "10/16/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - 5As.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

